/* Ishihara Plate generated by: https://franciscouzo.github.io/
 */

using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Xml.Linq;
using UnityEngine;
//using static UnityEditor.PlayerSettings;

public class SVGCircleReader : MonoBehaviour
{
    public GameObject CircleAsset;
    public CircleContainer testplate;
    //public Texture2D CircleAsset;

    //private properties
    private XDocument originalSVG;
    private List<CircleData> allCircles;




    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        string path = Path.Combine(Application.streamingAssetsPath, "ishiharaBlank.svg");
        if (!File.Exists(path))
        {
            Debug.LogError("No file found at: " + path);
            return;
        }

        originalSVG = XDocument.Load(path);


        allCircles = ReadValues();
        CreateGOwithParent(allCircles);

        
        
        /*foreach (var el in allCircles)
        {
            Debug.Log("Kreis ist in Position: " + el.Position);
        }*/

    }

    // Update is called once per frame
    void Update()
    {
    }

    void CreateGOwithParent(List<CircleData> dat)
    {
        List<GameObject> children = new List<GameObject>();
        var parentContainer = new GameObject("CCTPlate");
        parentContainer.transform.position = Vector3.zero;
        
        //Punkte als Gameobjects erschaffen
        foreach (var el in dat)
        {
            GameObject go = Instantiate(CircleAsset, el.Position, Quaternion.identity, parentContainer.transform);
            go.transform.localScale = Vector3.one * el.Radius * 2f; // Durchmesser statt Radius
            children.Add(go);
        }

        //Mittelpunkt herausfinden
        //Erstmal BoundingBox aller Kreise zusammenfassen
        Renderer[] renderers = parentContainer.GetComponentsInChildren<Renderer>();

        if (renderers.Length == 0)
        {
            Debug.LogWarning("Keine Renderer in den Childs gefunden.");
            return;
        }

        // Bounds der Child-Renderer zusammenfassen
        Bounds bounds = renderers[0].bounds;
        foreach (var rend in renderers)
        {
            bounds.Encapsulate(rend.bounds);
        }

        Vector3 center = bounds.center;

        foreach (GameObject go in children)
        {
            go.transform.position = go.transform.position - center;
        }
    }

    void CreateGOwithParent()
    {
        var dat = allCircles;
        List<GameObject> children = new List<GameObject>();
        var parentContainer = new GameObject("CCTPlate");
        parentContainer.transform.position = Vector3.zero;

        //Punkte als Gameobjects erschaffen
        foreach (var el in dat)
        {
            GameObject go = Instantiate(CircleAsset, el.Position, Quaternion.identity, parentContainer.transform);
            go.transform.localScale = Vector3.one * el.Radius * 2f; // Durchmesser statt Radius
            //go.GetComponentInChildren<SpriteRenderer>().sortingLayerName = "OverPanel";
            //go.GetComponentInChildren<SpriteRenderer>().sortingOrder = 1;
            children.Add(go);
        }

        //Mittelpunkt herausfinden
        //Erstmal Renderer aller Kreise sammeln
        Renderer[] renderers = parentContainer.GetComponentsInChildren<Renderer>();

        if (renderers.Length == 0)
        {
            Debug.LogWarning("Keine Renderer in den Childs gefunden.");
            return;
        }

        // Bounds der Child-Renderer zusammenfassen
        Bounds bounds = renderers[0].bounds;
        foreach (var rend in renderers)
        {
            bounds.Encapsulate(rend.bounds);
        }

        Vector3 center = bounds.center;

        foreach (GameObject go in children)
        {
            go.transform.position = go.transform.position - center;
        }
    }

    void CreateGO(List<CircleData> dat)
    {
        foreach (var el in dat)
        {
            GameObject go = Instantiate(CircleAsset, el.Position, Quaternion.identity, this.transform);
            go.transform.localScale = Vector3.one * el.Radius * 2f; // Durchmesser statt Radius
        }
        
    }

    List<CircleData> ReadValues()
    {
        List<CircleData> myCircles = new List<CircleData>();

        foreach (var elem in originalSVG.Descendants("{http://www.w3.org/2000/svg}circle"))
        {
            var x = float.Parse(elem.Attribute("cx").Value, CultureInfo.InvariantCulture);
            var y = float.Parse(elem.Attribute("cy").Value, CultureInfo.InvariantCulture);
            var r = float.Parse(elem.Attribute("r").Value, CultureInfo.InvariantCulture);
            //Debug.Log("this circle is in Xpos: " + x);

            // Das Internet sagt, SVGs positive Y-Werte gehen nach unten und Unitys Y nach oben. Darum invertiert
            var cPos = new Vector3(x, -y, 0);
            CircleData currentCircle = new CircleData(cPos, r);

            myCircles.Add(currentCircle);

            //neues Experiment: mit dem Struct Circle Container die Bounds direkt in mein Objekt backen
            CreatePlateArea(currentCircle);
        }

        Debug.Log("Die Kreise liegen im Bereich: Min " + testplate.Bounds2DMin + " und Max " + testplate.Bounds2DMax);
        return myCircles;
    }

    void CreatePlateArea(CircleData dat) //wird glaube ich nicht mehr gebraucht. Relikt aus der Zeit, bevor ich die Bounds nutzen konnte
    {
        //update die Minimalwerte
        testplate.Bounds2DMin.x = Mathf.Min(testplate.Bounds2DMin.x, dat.Position.x);
        testplate.Bounds2DMin.y = Mathf.Min(testplate.Bounds2DMin.y, dat.Position.y);

        //update die Maximalwerte
        testplate.Bounds2DMax.x = Mathf.Max(testplate.Bounds2DMax.x, dat.Position.x);
        testplate.Bounds2DMax.y = Mathf.Max(testplate.Bounds2DMax.y, dat.Position.y);
    }


    //sollte ich bald wenigstens teilweise wieder private schalten
    public struct CircleData
    {
        public Vector3 Position;
        public float Radius;

        //constructor
        public CircleData(Vector3 position, float radius)
        {
            Position = position;
            Radius = radius;
        }
    }

    public struct CircleContainer
    {
        public List<CircleData> Circles { get; private set; }
        public Vector2 Bounds2DMin;
        public Vector2 Bounds2DMax;

        //public CircleCollider2D Collider { get; private set; }
        
        //constructor
        public CircleContainer(List<CircleData> circles, Vector2 bounds2DMin, Vector2 bounds2DMax)
        {
            Circles = circles;
            Bounds2DMin = Vector2.zero;
            Bounds2DMax = Vector2.zero;
        }
    }
}
